export const PERSONAL_DETAILS = "PERSONAL_DETAILS"
export const WORK_EXPERIENCES = "WORK_EXPERIENCES"
export const EDUCATIONS = "EDUCATIONS"
export const PROJECTS = "PROJECTS"
export const LINKS = "LINKS"
export const SKILLS = "SKILLS"
